// GET POKEMONS

export const GET_POKEMONS_FAIL = 'GET_POKEMONS_FAIL';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';

export const GET_POKEMON_FAIL = 'GET_POKEMON_FAIL';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';

export const GET_POKEMONS_TYPE_FAIL = 'GET_POKEMONS_TYPE_FAIL';
export const GET_POKEMONS_TYPE_SUCCESS = 'GET_POKEMONS_TYPE_SUCCESS';

export const LOADING = 'LOADING';